name: Metrics FireHub Core
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: metrics-renders
          committer_message: "Update base metrics"
          template: repository
          user: The-FireHub-Project-old
          repo: TheCore
          filename: github-metrics-core-base.svg
          token: ${{ secrets.FIREHUB }}
          base_indepth: yes
