name: Metrics2
on:
  push:
    branches:
      - '*'
      #- '!master'
  pull_request:
    branches:
      - '*'
      #- '!master'
  # Schedule daily updates
  #schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manuallyy
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: metrics-renders
          committer_message: "Update metrics"
          template: classic
          filename: github-metrics2.svg
          token: ${{ secrets.FIREHUB }}
          base: header, activity, community, repositories, metadata

          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_timestamps: true

          plugin_code: yes
          plugin_code_days: 365
          plugin_code_languages: php

          plugin_followup: yes
          plugin_followup_indepth: yes
          
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_charts: yes
