name: Metrics2
on:
  push:
    branches:
      - '*'
      #- '!master'
  pull_request:
    branches:
      - '*'
      #- '!master'
  # Schedule daily updates
  #schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manuallyy
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: metrics-renders
          committer_message: "Update metrics"
          template: classic
          filename: github-metrics2.svg
          token: ${{ secrets.FIREHUB }}
          base: header, activity, community, repositories, metadata

          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_timestamps: true

          plugin_code: yes
          plugin_code_days: 365
          plugin_code_languages: php

          plugin_followup: yes
          plugin_followup_indepth: yes
          
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_charts: yes

          plugin_languages: yes
          plugin_languages_indepth: true
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_recent_categories: data, markup, programming, prose

          plugin_pagespeed: yes
          plugin_pagespeed_url: https://the-firehub-project.github.io/
          plugin_pagespeed_detailed: yes

          plugin_people: yes
          plugin_people_types: followers, following, sponsored, sponsors, members, thanks
          # plugin_people_thanks:

          plugin_projects: yes
          plugin_projects_repositories: The-FireHub-Project/projects/1, The-FireHub-Project/projects/2
          plugin_projects_descriptions: yes

          #plugin_rss: yes
          #plugin_rss_source: https://news.ycombinator.com/rss
