name: Metrics
on:
  push:
    branches:
      - '*'
      #- '!master'
  pull_request:
    branches:
      - '*'
      #- '!master'
  # Schedule daily updates
  #schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manuallyy
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: metrics-renders
          committer_message: "Update metrics"
          template: classic
          user: The-FireHub-Project-old
          repo: TheCore
          filename: github-metrics.svg
          token: ${{ secrets.FIREHUB }}
          base: header, activity, community, repositories, metadata
          
          plugin_activity: yes
          plugin_activity_visibility: public
          plugin_activity_timestamps: true
          
          #plugin_contributors: yes
          #plugin_contributors_head: ${{ github.head_ref || github.ref_name }}
          #plugin_contributors_contributions: yes
          #plugin_contributors_sections: categories
          #plugin_contributors_categories: |
          #  {
          #    "📚 Documentation":["README.md", "**/README.md"],
          #    "💻 Code (other)":["src/**", "Dockerfile"]
          #  }
            
          plugin_followup: yes
          plugin_followup_indepth: yes

          #plugin_habits: yes
          #plugin_habits_facts: yes
          #plugin_habits_charts: no
