name: Metrics
on:
  push:
    branches:
      - '*'
      #- '!master'
  pull_request:
    branches:
      - '*'
      #- '!master'
  # Schedule daily updates
  #schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: repository
          user: The-FireHub-Project-old
          repo: TheCore
          filename: github-metrics.svg
          token: ${{ secrets.FIREHUB }}
