name: Metrics The FreHub Project
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Update base
        uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: metrics-renders
          committer_message: "Update base metrics"
          template: classic
          filename: github-metrics-firehub-base.svg
          token: ${{ secrets.FIREHUB }}
          base_indepth: yes
      - name: Update activity
        uses: lowlighter/metrics@latest
        with:
          output_action: commit
          retries: 1
          retries_delay: 10
          committer_branch: metrics-renders
          committer_message: "Update activity metrics"
          template: classic
          filename: github-metrics-firehub-activity.svg
          token: ${{ secrets.FIREHUB }}
          base: ""
          plugin_activity: yes
          plugin_activity_days: 365
          plugin_activity_visibility: public
          plugin_activity_timestamps: true
